### ISSUE TITLE
can you please make this lgpl

### ISSUE THREAD

**Issue by acgreek** [2ion/libqueue#1]
I'd like to continue working on this and build a product using it but I can not unless you make it lgpl

**Comment by 2ion** [comment]
Sure, that's possible. Give me a second to exchange the headers.

**Comment by 2ion** [comment]
Turns out that the LGPL3 is an addition to the GPL3. Is the documentation added with 63cc774 sufficient for you?

**Comment by acgreek** [comment]
thank you. You're awesome
